export default {
  locale: state => state.common.locale,
  baseImageUrl: state => state.common.baseImageUrl,
  tabBarActive: state => state.common.tabBarActive,
  searchKeyWords: state => state.common.searchKeyWords,
  accessToken: state => state.common.accessToken,
  login: state => state.common.login,
  CODSTORE: state => state.common.CODSTORE,
  replyEmial: state => state.common.replyEmial,
  userInfo: state => state.common.userInfo,
  CODFEE: state => state.common.CODFEE,
  order: state => state.common.order,
  editAddress: state => state.common.editAddress,
  subOrderInfo: state => state.common.subOrderInfo,
  payMethods: state => state.common.payMethods,
  paymentForm: state => state.common.paymentForm,
  allinPayForm: state => state.common.allinPayForm,
  remark: state => state.common.remark,
  total: state => state.common.total,
  goodsId: state => state.common.goodsId,
  touristBuyInfo: state => state.common.touristBuyInfo,
  navNo: state => state.common.navNo,
  downApp: state => state.common.downApp,
  leaderId: state => state.common.leaderId,
  QYCode: state => state.common.QYCode
}
